"""
terrain.py - Scrolling terrain system for Scramble.

How the original works
----------------------
Each zone has a screen layout stored as semigraphic chars at $5E00-$61FF.
These chars are copied into video RAM ($3C00-$3FFF) by fn_copy_terrain
($6300) which uses an LDIR block move.  The terrain is then scrolled left
each frame by fn_scroll_screen ($64CA), which shifts all 16 rows of video
RAM one character column left.  New terrain column data is generated by
fn_update_terrain_height (.L6E7F) and written into the rightmost column.

fn_update_terrain_height (.L6E7F):
    Uses a 16-bit LFSR (state at $6ABE lo / $6ABF hi) seeded from the
    terrain-type table at $702C + (level_pos & $1F)*2.  Each call:
        1. If LFSR_lo bit 0 = 1:
               new_step = terrain_step + modifier
               if new_step >= $30 (48): skip (clamped)
               else: terrain_step = new_step
        2. Advance LFSR:
               h_bit0 = LFSR_hi & 1
               LFSR_lo >>= 1  ;  if h_bit0: LFSR_lo |= 0x80
               LFSR_hi >>= 1
               if LFSR_lo == 0: reload seed from $702C
    Modifier selection before each column:
        if terrain_step < $19 (25): modifier = +1
        elif terrain_step >= $2C (44): modifier = 0xFF (-1 signed)
        else: depends on level_pos bit 6 (+1 or -1)
    terrain_step ranges $00-$2F (0-47); initial value = $2F = 47.
    Ceiling height in pixels = PIXELS_TALL - terrain_step - FLOOR_RESERVE.

fn_draw_terrain ($6495):
    Converts height-byte chars: if char >= $80 it computes BF - (char-80)
    as the solid-block depth.  char $80 = 0 depth (blank), $BF = full block.
"""

from dataclasses import dataclass, field
from typing import Optional

from constants import (
    SCREEN_CHARS_WIDE, SCREEN_CHARS_TALL,
    PIXELS_WIDE, PIXELS_TALL,
    TERRAIN_COLS,
    ZONE_NAMES,
    TERRAIN_INIT_STEP, TERRAIN_SEED_TABLE,
    TERRAIN_CEILING_MIN, TERRAIN_CEILING_MAX,
    TERRAIN_FLOOR_MIN,   TERRAIN_FLOOR_MAX,
)
from trs80_screen import TRS80Screen


# ---------------------------------------------------------------------------
# Zone terrain definitions
# ---------------------------------------------------------------------------
# Each zone defines how the ceiling and floor heights vary as the player
# flies through it.  Heights are in logical pixel rows (0 = flush with
# top/bottom edge, positive values = terrain extends inward).
#
# These are reconstructed from the screen layout data in sectors 2–3 of
# the disk image.  The original stores pre-rendered screen tiles; we
# re-derive the underlying height data that produced those tiles.

@dataclass
class ZoneDefinition:
    """Terrain parameters for one zone."""
    name:            str
    # (min, max) ceiling height in logical pixels (0 = no ceiling)
    ceiling_range:   tuple[int, int]
    # (min, max) floor height in logical pixels (0 = no floor)
    floor_range:     tuple[int, int]
    # Column width before transitioning to the next zone
    zone_width_cols: int
    # Whether the terrain undulates (True) or is flat (False)
    undulating:      bool
    # Obstacles in this zone: list of (relative_col, row_from_top) char positions
    # None means procedurally generated from the height tables
    obstacles:       Optional[list] = None


# Zone definitions derived from the disk image screen data.
# Heights are in logical pixel rows (out of 48 total).
# The playable corridor is PIXELS_TALL (48) minus ceiling and floor heights.
ZONE_DEFINITIONS = [
    ZoneDefinition(
        name="FIGHTERS",
        ceiling_range=(3, 9),
        floor_range=(3, 9),
        zone_width_cols=96,
        undulating=True,
    ),
    ZoneDefinition(
        name="BLIMPS",
        ceiling_range=(3, 12),
        floor_range=(3, 9),
        zone_width_cols=96,
        undulating=True,
    ),
    ZoneDefinition(
        name="BOMBERS",
        ceiling_range=(6, 12),
        floor_range=(3, 9),
        zone_width_cols=96,
        undulating=False,
    ),
    ZoneDefinition(
        name="FORT",
        ceiling_range=(3, 9),
        floor_range=(6, 15),
        zone_width_cols=128,
        undulating=True,
    ),
    ZoneDefinition(
        name="FACTORY",
        ceiling_range=(6, 12),
        floor_range=(9, 18),
        zone_width_cols=128,
        undulating=False,
    ),
    ZoneDefinition(
        name="ROCKETS",
        ceiling_range=(3, 9),
        floor_range=(3, 9),
        zone_width_cols=96,
        undulating=True,
    ),
    ZoneDefinition(
        name="FUEL TANKS",
        ceiling_range=(3, 9),
        floor_range=(6, 12),
        zone_width_cols=128,
        undulating=False,
    ),
    ZoneDefinition(
        name="ARSENAL",
        ceiling_range=(6, 15),
        floor_range=(6, 15),
        zone_width_cols=160,
        undulating=True,
    ),
]


# ---------------------------------------------------------------------------
# Semigraphic char encoding helpers
# ---------------------------------------------------------------------------
# The original fn_draw_terrain ($6495) converts height to char via:
#   char = $BF - depth  where depth = (stored_char - $80)
# We replicate this logic to produce the correct block characters for the
# terrain walls.

def height_to_chars(
    height_px: int, from_top: bool
) -> list[int]:
    """
    Convert a terrain height in logical pixels to a list of character codes
    to write into the appropriate character rows.

    from_top=True  → ceiling (chars fill from row 0 downward)
    from_top=False → floor   (chars fill from row 15 upward)

    Each char row is 3 logical pixels tall.  A height of 6px = 2 full rows.
    The partial row at the boundary uses a partial semigraphic char.

    Returns a list of (char_code, row_index) pairs for all affected rows.
    """
    cells = []
    full_rows = height_px // 3
    remainder_px = height_px % 3

    if from_top:
        # Full solid rows at the top
        for r in range(full_rows):
            cells.append((0xBF, r))   # $BF = full 2×3 block
        # Partial row
        if remainder_px > 0:
            # Build char: fill the top `remainder_px` pixel rows of the cell
            bits = 0
            for py in range(remainder_px):
                # Both pixels in this row are ON
                for px in range(2):
                    bit_index = (2 - py) * 2 + (1 - px)
                    bits |= (1 << bit_index)
            cells.append((0x80 | bits, full_rows))
    else:
        # Floor: fills from bottom upward
        total_rows = SCREEN_CHARS_TALL
        for r in range(full_rows):
            cells.append((0xBF, total_rows - 1 - r))
        if remainder_px > 0:
            bits = 0
            for py in range(3 - remainder_px, 3):
                for px in range(2):
                    bit_index = (2 - py) * 2 + (1 - px)
                    bits |= (1 << bit_index)
            cells.append((0x80 | bits, total_rows - 1 - full_rows))

    return cells


# ---------------------------------------------------------------------------
# Terrain generator
# ---------------------------------------------------------------------------

class Terrain:
    """
    Generates and manages the scrolling terrain.

    Maintains two ring-buffer arrays:
      ceiling_heights[col] - ceiling height in logical pixels at each column
      floor_heights[col]   - floor height in logical pixels at each column

    Each frame, scroll() shifts the buffer left and generates new right-edge
    column data from the current zone definition.
    """

    def __init__(self) -> None:
        # Current terrain data for one screen's worth of columns plus lookahead
        self.ceiling_heights = [6] * TERRAIN_COLS
        self.floor_heights   = [6] * TERRAIN_COLS
        self._zone_index     = 0
        self._col_in_zone    = 0    # how many columns we have scrolled in this zone
        self._level_pos      = 0    # overall scroll position (for bit-6 modifier check)

        # LFSR state for ceiling (Z80 $6ABE/$6ABF pair, initial $FF00)
        # Separate LFSR for floor uses offset seed slot.
        self._zone_def           = ZONE_DEFINITIONS[0]
        self._ceiling_lfsr: int  = 0xFF00
        self._floor_lfsr:   int  = 0xFF00
        self._ceiling_step: int  = TERRAIN_INIT_STEP   # $2F = 47
        self._floor_step:   int  = TERRAIN_INIT_STEP
        # Modifier: +1 or -1 (unsigned byte value $FF = -1)
        # Initial modifier is -1 since step=47 is near the max ($30=48).
        self._ceiling_mod:  int  = -1
        self._floor_mod:    int  = -1

        # Initialise the full terrain buffer for the first zone
        self._load_lfsr_seed(0)
        for col in range(TERRAIN_COLS):
            self._generate_column(col)

    # ------------------------------------------------------------------
    # Public interface
    # ------------------------------------------------------------------

    @property
    def zone_index(self) -> int:
        return self._zone_index

    @property
    def zone_name(self) -> str:
        return self._zone_def.name

    def advance_zone(self) -> None:
        """Move to the next zone, wrapping around after the last."""
        self._zone_index = (self._zone_index + 1) % len(ZONE_DEFINITIONS)
        self._zone_def = ZONE_DEFINITIONS[self._zone_index]
        self._col_in_zone = 0
        self._load_lfsr_seed(self._zone_index)

    def scroll(self) -> None:
        """
        Scroll the terrain one character column to the left.
        Matches fn_scroll_screen ($64CA): shifts video RAM left, then
        the terrain system fills the new rightmost column.
        Called once per frame.
        """
        # Shift everything left
        self.ceiling_heights.pop(0)
        self.floor_heights.pop(0)
        # Generate new rightmost column
        self._generate_column(TERRAIN_COLS - 1)
        self._col_in_zone += 1
        self._level_pos   += 1
        # Check if we've completed this zone
        if self._col_in_zone >= self._zone_def.zone_width_cols:
            self.advance_zone()

    def get_ceiling_height(self, col: int) -> int:
        """Return ceiling height (pixels) for the given terrain column."""
        return self.ceiling_heights[min(col, TERRAIN_COLS - 1)]

    def get_floor_height(self, col: int) -> int:
        """Return floor height (pixels) for the given terrain column."""
        return self.floor_heights[min(col, TERRAIN_COLS - 1)]

    def is_in_terrain(self, pixel_x: int, pixel_y: int) -> bool:
        """
        Return True if the given logical pixel is inside terrain (ceiling or floor).
        Used for collision detection, mirroring the Z80 fn_check_ship_crash ($65C2)
        which reads video RAM and tests for non-blank chars.
        """
        # Map pixel_x to terrain column index (accounting for scroll)
        # For simplicity we use the leftmost visible columns
        col = min(pixel_x // 2, TERRAIN_COLS - 1)
        ceiling = self.ceiling_heights[col]
        floor_top = PIXELS_TALL - self.floor_heights[col]
        return pixel_y < ceiling or pixel_y >= floor_top

    def draw_to_screen(self, screen: TRS80Screen) -> None:
        """
        Write the currently visible terrain columns to the TRS-80 screen.
        Replicates fn_draw_terrain ($6495) and fn_copy_terrain ($6300).

        For each of the 64 visible character columns:
          - Write ceiling chars into rows 0..N  (from top)
          - Write floor chars into rows (16-M)..15 (from bottom)
          - Clear the space between them
        """
        for char_col in range(SCREEN_CHARS_WIDE):
            ceiling_px = self.ceiling_heights[char_col]
            floor_px   = self.floor_heights[char_col]

            # Clear the entire column to blank first
            for char_row in range(SCREEN_CHARS_TALL):
                screen.write_char(char_col, char_row, 0x80)

            # Write ceiling
            for char_code, char_row in height_to_chars(ceiling_px, from_top=True):
                screen.write_char(char_col, char_row, char_code)

            # Write floor
            for char_code, char_row in height_to_chars(floor_px, from_top=False):
                screen.write_char(char_col, char_row, char_code)

    # ------------------------------------------------------------------
    # Private terrain generation  (LFSR algorithm from .L6E7F)
    # ------------------------------------------------------------------

    def _load_lfsr_seed(self, zone_idx: int) -> None:
        """
        Load LFSR seed from TERRAIN_SEED_TABLE for the given zone.
        Mirrors the seed reload from $702C + (level_pos & $1F)*2.
        Ceiling uses slot (zone_idx & 0x1F), floor uses offset slot.
        """
        slot_c = (zone_idx * 2) & 0x1F      # ceiling slot (even index)
        slot_f = (zone_idx * 2 + 1) & 0x1F  # floor slot (odd index)
        byte_c = slot_c * 2
        byte_f = slot_f * 2
        lo_c = TERRAIN_SEED_TABLE[byte_c]
        hi_c = TERRAIN_SEED_TABLE[byte_c + 1]
        lo_f = TERRAIN_SEED_TABLE[byte_f]
        hi_f = TERRAIN_SEED_TABLE[byte_f + 1]
        self._ceiling_lfsr = (hi_c << 8) | lo_c
        self._floor_lfsr   = (hi_f << 8) | lo_f
        # Ensure non-zero (LFSR must not start at 0)
        if self._ceiling_lfsr == 0:
            self._ceiling_lfsr = 0xFF00
        if self._floor_lfsr == 0:
            self._floor_lfsr = 0xFF00

    def _advance_lfsr(self, lfsr: int) -> tuple[int, bool]:
        """
        Advance the 16-bit LFSR by one step.
        Mirrors the shift sequence in .L6E7F:
            bit0 = LFSR_lo & 1
            h_bit0 = LFSR_hi & 1
            LFSR_lo >>= 1  (SRL)
            if h_bit0: LFSR_lo |= 0x80   (carry from hi)
            LFSR_hi >>= 1  (SRL)
            if LFSR_lo == 0: reload seed

        Returns (new_lfsr, ticked) where ticked=True when bit0 was set
        (the condition that triggers a terrain_step update).
        """
        lo = lfsr & 0xFF
        hi = (lfsr >> 8) & 0xFF
        ticked = bool(lo & 1)
        h_bit0 = hi & 1
        lo = (lo >> 1) & 0xFF
        if h_bit0:
            lo |= 0x80
        hi = (hi >> 1) & 0xFF
        new_lfsr = (hi << 8) | lo
        # If lo went to 0, reload — use a stable non-zero fallback seed
        if lo == 0:
            new_lfsr = 0xFF00
        return new_lfsr, ticked

    def _update_modifier(self, step: int) -> int:
        """
        Determine the terrain_step modifier for the next column.
        Mirrors the pre-column modifier selection in .L6E7F:
            if step < $19 (25)  : modifier = +1  (terrain grows inward)
            if step >= $2C (44) : modifier = -1  (terrain shrinks back)
            else                 : depends on level_pos bit 6
        """
        if step < 25:
            return 1
        elif step >= 44:
            return -1
        else:
            # level_pos bit 6: alternates every 64 columns
            return 1 if (self._level_pos & 0x40) else -1

    def _lfsr_step(self, lfsr: int, step: int, mod: int) -> tuple[int, int, int]:
        """
        Perform one LFSR step and optionally update terrain_step.
        Mirrors the inner loop of fn_update_terrain_height (.L6E7F).

        Returns (new_lfsr, new_step, new_mod).
        """
        new_lfsr, ticked = self._advance_lfsr(lfsr)
        if ticked:
            candidate = step + mod
            if 0 <= candidate < 48:   # clamp: not >= $30
                step = candidate
        new_mod = self._update_modifier(step)
        return new_lfsr, step, new_mod

    def _step_to_height(self, step: int, lo: int, hi: int) -> int:
        """
        Map terrain_step (0-47) to a pixel height clamped to [lo, hi].
        step=47 → minimal terrain (open sky/ground)
        step=0  → maximal terrain (thick wall)
        """
        # Invert and scale: step decreases as terrain grows inward
        scaled = int((47 - step) * (hi - lo) / 47 + lo)
        return max(lo, min(hi, scaled))

    def _generate_column(self, col: int) -> None:
        """
        Generate terrain heights for one new column using the LFSR.
        Mirrors fn_update_terrain_height (.L6E7F) + fn_draw_terrain ($6495).
        The LFSR drives terrain_step which is converted to pixel heights.
        """
        # Advance LFSR for ceiling and floor independently
        self._ceiling_lfsr, self._ceiling_step, self._ceiling_mod = (
            self._lfsr_step(self._ceiling_lfsr, self._ceiling_step, self._ceiling_mod)
        )
        self._floor_lfsr, self._floor_step, self._floor_mod = (
            self._lfsr_step(self._floor_lfsr, self._floor_step, self._floor_mod)
        )

        self.ceiling_heights[col] = self._step_to_height(
            self._ceiling_step, TERRAIN_CEILING_MIN, TERRAIN_CEILING_MAX
        )
        self.floor_heights[col] = self._step_to_height(
            self._floor_step, TERRAIN_FLOOR_MIN, TERRAIN_FLOOR_MAX
        )
